### ISSUE TITLE
Exception thrown when running

### ISSUE THREAD

**Issue by damiangreen** [Particular/NServiceBus.Msmq.Samples#10]
Exception:Thrown: "The requested Performance Counter is not a custom counter, it has to be initialized as ReadOnly." (System.InvalidOperationException)
A System.InvalidOperationException was thrown: "The requested Performance Counter is not a custom counter, it has to be initialized as ReadOnly."
 Documentation / 001_OrderingSendOnly / Solution

**Comment by SimonCropp** [comment]
this sample has moved here http://docs.particular.net/samples/show-case/on-premise/ https://github.com/Particular/docs.particular.net/tree/master/samples/show-case/on-premise

I have raise an issue to track prereqs Particular/docs.particular.net#609
