### ISSUE TITLE
Put in readme how to actually run this

### ISSUE THREAD

**Issue by togakangaroo** [Particular/NServiceBus.Msmq.Samples#2]
I cloned this and have no idea how to run it.

I found an sln in one of the folders, and after running figured out to install msmq, but even then it still doesn't run crashing with complaints about not being to connect to a raven server.

Please add to the readme how to actually run the darn thing.

**Comment by SimonCropp** [comment]
@togakangaroo sorry for not addressing this sooner. this sample has moved here http://docs.particular.net/samples/show-case/on-premise/ https://github.com/Particular/docs.particular.net/tree/master/samples/show-case/on-premise

Regarding your specific issues... the raven db issue should now be resolved. And yes the samples need better guidance. I have raise an issue to track that https://github.com/Particular/docs.particular.net/issues/609
