### ISSUE TITLE
fit Scaleout to v5

### ISSUE THREAD

**Issue by israelio** [Particular/NServiceBus.Msmq.Samples#7]
In order to make this sample work seamlessly with v5 there is a need to:
add references to NServiceBus.Distributor.MSMQ.dll in the project for the distributor profiles to be available.
add documentation explaining people how to run with these profiles outside of visual studio
add configuration.EnableInstallers() to easily create queues while running the sample and enable the persistence storage so people who do try to run the distributor wont get an exception.
add App.config setting for the distributor on the workers.

At the current state this sample demonstrate competing queues and not a distributor scaleout.

**Comment by SimonCropp** [comment]
this sample has moved here http://docs.particular.net/samples/show-case/on-premise/ https://github.com/Particular/docs.particular.net/tree/master/samples/show-case/on-premise
